//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowMage.OverlayPlugin.Updater {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RainbowMage.OverlayPlugin.Updater.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Update check for {0} through ACT failed, retrying with GitHub API. 的本地化字符串。
        /// </summary>
        public static string ActUpdateCheckFailed {
            get {
                return ResourceManager.GetString("ActUpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACT Update check for {0} failed, falling back to GitHub API: {1} 的本地化字符串。
        /// </summary>
        public static string ActUpdateException {
            get {
                return ResourceManager.GetString("ActUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create or empty the temporary directory &quot;{0}&quot;: {1} 的本地化字符串。
        /// </summary>
        public static string CreatingTempDirFailed {
            get {
                return ResourceManager.GetString("CreatingTempDirFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download failed! The download has no file size (Content-Length header is missing). 的本地化字符串。
        /// </summary>
        public static string DownloadFailedContentLengthMissing {
            get {
                return ResourceManager.GetString("DownloadFailedContentLengthMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Error 的本地化字符串。
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed: {0} 的本地化字符串。
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring auto-update due to OverlayPlugin being a .git repo..
        /// </summary>
        public static string IgnoreUpdateDueToDotGitDirectoryMessage {
            get {
                return ResourceManager.GetString("IgnoreUpdateDueToDotGitDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to launch installer: {0} 的本地化字符串。
        /// </summary>
        public static string LaunchingInstallerFailed {
            get {
                return ResourceManager.GetString("LaunchingInstallerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] libcurl {
            get {
                object obj = ResourceManager.GetObject("libcurl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] libcurl_x64 {
            get {
                object obj = ResourceManager.GetObject("libcurl_x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted by user..
        /// </summary>
        public static string LogAbortedByUser {
            get {
                return ResourceManager.GetString("LogAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backing up old files... 的本地化字符串。
        /// </summary>
        public static string LogBackingUpOldFiles {
            get {
                return ResourceManager.GetString("LogBackingUpOldFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleaning up... 的本地化字符串。
        /// </summary>
        public static string LogCleaningUp {
            get {
                return ResourceManager.GetString("LogCleaningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting temporary files... 的本地化字符串。
        /// </summary>
        public static string LogDeletingTempFiles {
            get {
                return ResourceManager.GetString("LogDeletingTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done. 的本地化字符串。
        /// </summary>
        public static string LogDone {
            get {
                return ResourceManager.GetString("LogDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download failed: {0} 的本地化字符串。
        /// </summary>
        public static string LogDownloadFailed {
            get {
                return ResourceManager.GetString("LogDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading &quot;{0}&quot; into {1}... 的本地化字符串。
        /// </summary>
        public static string LogDownloading {
            get {
                return ResourceManager.GetString("LogDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The download was interrupted: {0} 的本地化字符串。
        /// </summary>
        public static string LogDownloadInterrupted {
            get {
                return ResourceManager.GetString("LogDownloadInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting files... 的本地化字符串。
        /// </summary>
        public static string LogExtractingFiles {
            get {
                return ResourceManager.GetString("LogExtractingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extraction aborted by user. 的本地化字符串。
        /// </summary>
        public static string LogExtractionAbortedByUser {
            get {
                return ResourceManager.GetString("LogExtractionAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to replace old directory: {0} 的本地化字符串。
        /// </summary>
        public static string LogFailedReplaceDirectory {
            get {
                return ResourceManager.GetString("LogFailedReplaceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to delete {0}: {1} 的本地化字符串。
        /// </summary>
        public static string LogFailedToDelete {
            get {
                return ResourceManager.GetString("LogFailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: The installer did not finish correctly. 的本地化字符串。
        /// </summary>
        public static string LogInstallerFailed {
            get {
                return ResourceManager.GetString("LogInstallerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for installer to exit... 的本地化字符串。
        /// </summary>
        public static string LogInstallerWaiting {
            get {
                return ResourceManager.GetString("LogInstallerWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launching installer... 的本地化字符串。
        /// </summary>
        public static string LogLaunchingInstaller {
            get {
                return ResourceManager.GetString("LogLaunchingInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving directory... 的本地化字符串。
        /// </summary>
        public static string LogMovingDirectory {
            get {
                return ResourceManager.GetString("LogMovingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening archive... 的本地化字符串。
        /// </summary>
        public static string LogOpeningArchive {
            get {
                return ResourceManager.GetString("LogOpeningArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No retries left, update failed. 的本地化字符串。
        /// </summary>
        public static string LogOverwriteFailed {
            get {
                return ResourceManager.GetString("LogOverwriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to overwrite {0}, retrying...
        ///{1} 的本地化字符串。
        /// </summary>
        public static string LogOverwriteRetry {
            get {
                return ResourceManager.GetString("LogOverwriteRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwriting old files... 的本地化字符串。
        /// </summary>
        public static string LogOverwritingOldFiles {
            get {
                return ResourceManager.GetString("LogOverwritingOldFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to overwrite old files: {0}
        ///WARNING: The plugin might be in an unusable state!!
        ///Run the update check again or reinstall the plugin, otherwise it might not survive the next ACT restart. 的本地化字符串。
        /// </summary>
        public static string LogOverwritingOldFilesFailed {
            get {
                return ResourceManager.GetString("LogOverwritingOldFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing old backup directory... 的本地化字符串。
        /// </summary>
        public static string LogRemovingOldBackup {
            get {
                return ResourceManager.GetString("LogRemovingOldBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restoring backup... 的本地化字符串。
        /// </summary>
        public static string LogRestoringBackup {
            get {
                return ResourceManager.GetString("LogRestoringBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resuming download... 的本地化字符串。
        /// </summary>
        public static string LogResumingDownload {
            get {
                return ResourceManager.GetString("LogResumingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying again... 的本地化字符串。
        /// </summary>
        public static string LogRetry {
            get {
                return ResourceManager.GetString("LogRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrying in 1 second. 的本地化字符串。
        /// </summary>
        public static string LogRetryAfter1s {
            get {
                return ResourceManager.GetString("LogRetryAfter1s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MSVCRT installation failed. 的本地化字符串。
        /// </summary>
        public static string MsvcrtFailed {
            get {
                return ResourceManager.GetString("MsvcrtFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re missing the MS Visual C++ Redistributable for Visual Studio 2019.
        ///You&apos;ll need that for OverlayPlugin. Install it now? 的本地化字符串。
        /// </summary>
        public static string MsvcrtMissing {
            get {
                return ResourceManager.GetString("MsvcrtMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out of retries. 的本地化字符串。
        /// </summary>
        public static string OutOfRetries {
            get {
                return ResourceManager.GetString("OutOfRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OverlayPlugin 的本地化字符串。
        /// </summary>
        public static string OverlayPluginTitle {
            get {
                return ResourceManager.GetString("OverlayPluginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The currently loaded version of SharpCompress is outdated!
        ///Make sure you load OverlayPlugin before any other plugins that also use SharpCompress (like ACTWebSocket). 的本地化字符串。
        /// </summary>
        public static string SharpCompressOutdatedError {
            get {
                return ResourceManager.GetString("SharpCompressOutdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancelled! 的本地化字符串。
        /// </summary>
        public static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancelling... 的本地化字符串。
        /// </summary>
        public static string StatusCancelling {
            get {
                return ResourceManager.GetString("StatusCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}/{1}]: Done. 的本地化字符串。
        /// </summary>
        public static string StatusDone {
            get {
                return ResourceManager.GetString("StatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}/{1}]: Downloading... 的本地化字符串。
        /// </summary>
        public static string StatusDownloadStarted {
            get {
                return ResourceManager.GetString("StatusDownloadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}/{1}]: Launching installer... 的本地化字符串。
        /// </summary>
        public static string StatusLaunchingInstaller {
            get {
                return ResourceManager.GetString("StatusLaunchingInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}/{1}]: Preparing extraction... 的本地化字符串。
        /// </summary>
        public static string StatusPreparingExtraction {
            get {
                return ResourceManager.GetString("StatusPreparingExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are already on the latest version. 的本地化字符串。
        /// </summary>
        public static string UpdateAlreadyLatest {
            get {
                return ResourceManager.GetString("UpdateAlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to download CEF! Check the OverlayPlugin.dll tab for details. 的本地化字符串。
        /// </summary>
        public static string UpdateCefDlFailed {
            get {
                return ResourceManager.GetString("UpdateCefDlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check for updates:
        ///{0} 的本地化字符串。
        /// </summary>
        public static string UpdateCheckException {
            get {
                return ResourceManager.GetString("UpdateCheckException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Update Check 的本地化字符串。
        /// </summary>
        public static string UpdateCheckTitle {
            get {
                return ResourceManager.GetString("UpdateCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to update the plugin. It might not load the next time you start ACT. Retry? 的本地化字符串。
        /// </summary>
        public static string UpdateFailedError {
            get {
                return ResourceManager.GetString("UpdateFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to parse version:
        ///{0} 的本地化字符串。
        /// </summary>
        public static string UpdateParseVersionError {
            get {
                return ResourceManager.GetString("UpdateParseVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} was updated successfully. 的本地化字符串。
        /// </summary>
        public static string UpdateSliderDetails {
            get {
                return ResourceManager.GetString("UpdateSliderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The update was successful. Please restart ACT to load the new plugin version. 的本地化字符串。
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Update 的本地化字符串。
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
    }
}
