name: Check linting

on:
  push:
    branches:
      - 'main'
    paths:
      - '**/*.cs'
      - '.editorconfig'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**/*.cs'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  msbuild:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Add Custom Problem Matcher
        run: |
          echo "::add-matcher::.github/matchers/dotnet-format.json"

      - name: Run Build
        run: dotnet format --verify-no-changes
        shell: cmd
